name: "Check action updates"
description: "Github action that scans workflow and check if available updates"
author: "Rahul Patil"
inputs:
  ignoreActions:
    required: false
    description: "Provide list of action that you want to ignore"
    default: ""
  workflowDir:
    required: false
    description: "Provide workflow directory path"
    default: .github/workflows
  loglevel:
    required: false
    description: "Set log level: debug, error, warn"
    default: "info"
  prettyprint:
    required: false
    description: "Get json dump with prettyprint"
    default: "true"

outputs:
  actions:
    description: "List of available updates"
runs:
  using: "docker"
  image: "Dockerfile"
