name: Integration Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sergeysova/jq-action@v2
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: rahulinux/gh-check-action@main

      - name: Check outputs
        run: |
          diff <( jq --sort-keys . "${{ steps.selftest.outputs.actions }}") <(jq --sort-keys . expected.json)
