name: Integration Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sergeysova/jq-action@v2
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: rahulinux/gh-check-action@main
        with:
          workflowDir: "/github/workspace/.github/workflows"
          loglevel: "debug"
          prettyprint: "false"

      - name: Check outputs
        run: |
          echo '${{ steps.selftest.outputs.actions }}' > output.json
          echo '{"/github/workspace/.github/workflows":{"rahulinux/gh-check-action@main":"rahulinux/gh-check-action@v1"}}' > expected.json
          diff <( jq --sort-keys . output.json) <(jq --sort-keys . expected.json)
